# Generated by Django 5.1.1 on 2024-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_alter_prebooking_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebooking",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
